### ISSUE TITLE
When you pick a region, then return, and pick other one, it picks the first one

### ISSUE THREAD

**Issue by ghost** [RiiConnect24/.VFF-File-Downloader-for-Dolphin#3] opened 2020-04-03 19:33 UTC
As the title day, for example, you pick Japan, and then return, and you pick Brazil, it will pick Japan

**Comment by KcrPL** [comment] 2020-04-03 19:41
Cannot reproduce.

Closing for now. Can you try redownloading the Install.bat?

**Closed as completed by KcrPL** 2020-04-03 19:41 UTC
Labels: invalid
